Update .drone.yml
UKHomeOffice/hocs-docs-converter pull request #67
Opened 2021-11-15 11:49 UTC by nickmcmahon01

Do not build & push quay image on dependabot PRs

2021-11-19 10:35 UTC, LiamMacP approved these changes

2021-11-19 10:37 UTC, LiamMacP requested changes
This would also need the `build and push main` to have the correct tags added.

2021-11-23 15:33 UTC, LiamMacP commented
Inerested if this works? Does Drone understand this kind of pathing? might need to be `"dependabot*"`..?

2021-11-23 15:33 UTC, nickmcmahon01 commented
This change has been made in HOCS-4030

2021-11-24 09:12 UTC, merged